insert into Users (first_name, last_name, admin) values ('Adrienne', 'Thom', true);
insert into Users (first_name, last_name, admin) values ('Barbe', 'Gundrey', null);
insert into Users (first_name, last_name, admin) values ('Bobby', 'Cornford', null);
insert into Users (first_name, last_name, admin) values ('Chrysler', 'Malster', null);
insert into Users (first_name, last_name, admin) values ('Alastair', 'Hrihorovich', null);
insert into Users (first_name, last_name, admin) values ('Koressa', 'Syddon', null);
insert into Users (first_name, last_name, admin) values ('Harmon', 'Zupone', null);
insert into Users (first_name, last_name, admin) values ('Murray', 'Feler', null);
insert into Users (first_name, last_name, admin) values ('Byram', 'Tuffley', null);
insert into Users (first_name, last_name, admin) values ( 'Kat', 'Monson', null);
insert into Users (first_name, last_name, admin) values ( 'Maurice', 'Charte', null);
insert into Users (first_name, last_name, admin) values ( 'Andonis', 'Lindbergh', null);
insert into Users (first_name, last_name, admin) values ( 'Farlay', 'Stare', null);
insert into Users (first_name, last_name, admin) values ( 'Putnem', 'Teers', null);
insert into Users (first_name, last_name, admin) values ( 'Jacqui', 'Sarchwell', null);
insert into Users (first_name, last_name, admin) values ( 'Arnuad', 'Murrell', null);
insert into Users (first_name, last_name, admin) values ( 'Jase', 'Goodbourn', null);
insert into Users (first_name, last_name, admin) values ( 'Cyrillus', 'Capeling', null);
insert into Users (first_name, last_name, admin) values ( 'Kennedy', 'Hame', null);
insert into Users (first_name, last_name, admin) values ( 'Gus', 'Playdon', null);
insert into Users (first_name, last_name, admin) values ( 'Ivy', 'Colicot', null);
insert into Users (first_name, last_name, admin) values ( 'Britney', 'Jantot', null);
insert into Users (first_name, last_name, admin) values ( 'Hi', 'Hallan', null);
insert into Users (first_name, last_name, admin) values ( 'Courtnay', 'Bynert', null);
insert into Users (first_name, last_name, admin) values ( 'Maurice', 'Rivers', null);
insert into Users (first_name, last_name, admin) values ( 'Chaim', 'Cheney', null);
insert into Users (first_name, last_name, admin) values ( 'Shalom', 'Steaning', null);
insert into Users (first_name, last_name, admin) values ( 'Jocelin', 'Vater', null);
insert into Users (first_name, last_name, admin) values ( 'Britteny', 'Drever', null);
insert into Users (first_name, last_name, admin) values ( 'Carline', 'Bardwall', null);
insert into Users (first_name, last_name, admin) values ( 'Nanice', 'O''Hogertie', null);
insert into Users (first_name, last_name, admin) values ( 'Nydia', 'Shane', null);
insert into Users (first_name, last_name, admin) values ( 'Jozef', 'Hause', null);
insert into Users (first_name, last_name, admin) values ( 'Simonette', 'Kensington', null);
insert into Users (first_name, last_name, admin) values ( 'Faina', 'Leathes', null);
insert into Users (first_name, last_name, admin) values ( 'Jojo', 'Trigwell', null);
insert into Users (first_name, last_name, admin) values ( 'Emmey', 'Lottrington', null);
insert into Users (first_name, last_name, admin) values ( 'Ethe', 'Gullyes', null);
insert into Users (first_name, last_name, admin) values ( 'Orly', 'Suston', null);
insert into Users (first_name, last_name, admin) values ( 'Elfra', 'Kenworthey', null);
insert into Users (first_name, last_name, admin) values ( 'Faye', 'Bosence', null);
insert into Users (first_name, last_name, admin) values ( 'Ware', 'Snary', null);
insert into Users (first_name, last_name, admin) values ( 'Kaitlyn', 'Droogan', null);
insert into Users (first_name, last_name, admin) values ( 'Jonah', 'Leason', null);
insert into Users (first_name, last_name, admin) values ( 'Florance', 'Mitchener', null);
insert into Users (first_name, last_name, admin) values ( 'Giovanna', 'Pattlel', null);
insert into Users (first_name, last_name, admin) values ( 'Candie', 'Guitton', null);
insert into Users (first_name, last_name, admin) values ( 'Godard', 'Colliford', null);
insert into Users (first_name, last_name, admin) values ( 'Yank', 'Root', null);
insert into Users (first_name, last_name, admin) values ( 'Clem', 'Deverose', null);
insert into Users (first_name, last_name, admin) values ( 'Isador', 'Grabbam', null);
insert into Users (first_name, last_name, admin) values ( 'Adam', 'Swetland', null);
insert into Users (first_name, last_name, admin) values ( 'Maude', 'wal Evans', null);
insert into Users (first_name, last_name, admin) values ( 'Elyssa', 'Vedntyev', null);
insert into Users (first_name, last_name, admin) values ( 'Benedict', 'Manach', null);
insert into Users (first_name, last_name, admin) values ( 'Erskine', 'Dadge', null);
insert into Users (first_name, last_name, admin) values ( 'Warde', 'Timlin', null);
insert into Users (first_name, last_name, admin) values ( 'Hilly', 'Jollie', null);
insert into Users (first_name, last_name, admin) values ( 'Michelle', 'Hakes', null);
insert into Users (first_name, last_name, admin) values ( 'Hailey', 'Coleford', null);
insert into Users (first_name, last_name, admin) values ( 'Muffin', 'Grunguer', null);
insert into Users (first_name, last_name, admin) values ( 'Donaugh', 'Pickford', null);
insert into Users (first_name, last_name, admin) values ( 'Miller', 'Van Brug', null);
insert into Users (first_name, last_name, admin) values ( 'Allissa', 'Downham', null);
insert into Users (first_name, last_name, admin) values ( 'Antin', 'Bemlott', null);
insert into Users (first_name, last_name, admin) values ( 'Milzie', 'Bartod', null);
insert into Users (first_name, last_name, admin) values ( 'Misha', 'Beggan', null);
insert into Users (first_name, last_name, admin) values ( 'Anica', 'Inchan', null);
insert into Users (first_name, last_name, admin) values ( 'Bobina', 'Kitney', null);
insert into Users (first_name, last_name, admin) values ( 'Codie', 'Sowte', null);
insert into Users (first_name, last_name, admin) values ( 'Julia', 'Mera', null);
insert into Users (first_name, last_name, admin) values ( 'Tisha', 'Haliburton', null);
insert into Users (first_name, last_name, admin) values ( 'Emilie', 'Boissieux', null);
insert into Users (first_name, last_name, admin) values ( 'Alanna', 'Gommey', null);
insert into Users (first_name, last_name, admin) values ( 'Orly', 'Fosse', null);
insert into Users (first_name, last_name, admin) values ( 'Eliot', 'Scales', null);
insert into Users (first_name, last_name, admin) values ( 'Dusty', 'McCleod', null);
insert into Users (first_name, last_name, admin) values ( 'Geneva', 'Gerdts', null);
insert into Users (first_name, last_name, admin) values ( 'Hinda', 'Llorens', null);
insert into Users (first_name, last_name, admin) values ( 'Zacharia', 'Vanderson', null);
insert into Users (first_name, last_name, admin) values ( 'Ed', 'Axell', null);
insert into Users (first_name, last_name, admin) values ( 'ette', 'Cassedy', null);
insert into Users (first_name, last_name, admin) values ( 'Olivier', 'Aucock', null);
insert into Users (first_name, last_name, admin) values ( 'Fleur', 'McLaughlin', null);
insert into Users (first_name, last_name, admin) values ( 'Spenser', 'Burch', null);
insert into Users (first_name, last_name, admin) values ( 'Cory', 'Jonah', null);
insert into Users (first_name, last_name, admin) values ( 'Abigale', 'End', null);
insert into Users (first_name, last_name, admin) values ( 'Wye', 'Cancellario', null);
insert into Users (first_name, last_name, admin) values ( 'Retha', 'Ruegg', null);
insert into Users (first_name, last_name, admin) values ( 'Krystalle', 'Greenham', null);
insert into Users (first_name, last_name, admin) values ( 'Fey', 'Wolfenden', null);
insert into Users (first_name, last_name, admin) values ( 'Garvin', 'Spatari', null);
insert into Users (first_name, last_name, admin) values ( 'Normie', 'Husband', null);
insert into Users (first_name, last_name, admin) values ( 'Lamont', 'Minthorpe', null);
insert into Users (first_name, last_name, admin) values ( 'Nadia', 'Drayn', null);
insert into Users (first_name, last_name, admin) values ( 'Sabra', 'Silber', null);
insert into Users (first_name, last_name, admin) values ( 'Dallas', 'Escalera', null);
insert into Users (first_name, last_name, admin) values ( 'Krystalle', 'Charlick', null);
insert into Users (first_name, last_name, admin) values ( 'Nathaniel', 'McNeice', null);
insert into Users (first_name, last_name, admin) values ( 'Alejandro', 'Boscher', null);
