insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (1, 'vulputate nonummy maecenas', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 810, 4, 240, 'Gavrielle', 'Tamplin', '5672 Tomscot Alley', '613-190-2727', 'gtamplin0@google.it');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (2, 'risus auctor', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Quote Requested', 630, 10, 60, 'Britney', 'Kauscher', '36066 Onsgard Circle', '116-265-9492', 'bkauscher1@seesaa.net');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (3, 'consequat lectus in est', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Quote Requested', 720, 6, 210, 'Corenda', 'Shellum', '08144 Lighthouse Bay Plaza', '626-294-7421', 'cshellum2@cisco.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (4, 'nulla sed vel enim', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Quote Requested', 1110, 1, 90, 'Aldis', 'Lamacraft', '838 Jenna Pass', '861-485-9575', 'alamacraft3@google.com.br');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (5, 'nisi eu orci', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Quote Requested', 1260, 9, 60, 'Martynne', 'Filipov', '425 Maryland Court', '207-594-1988', 'mfilipov4@unc.edu');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (6, 'cras in purus eu', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'done', 900, 1, 150, 'Vivien', 'Brettle', '34 Lukken Way', '845-405-5369', 'vbrettle5@wordpress.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (7, 'dolor morbi vel', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'in process', 660, 8, 30, 'Honoria', 'Cuer', '2100 Lakewood Gardens Place', '708-905-3354', 'hcuer6@ft.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (8, 'nisl aenean', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Quote Requested', 1200, 3, 90, 'Abner', 'Bowering', '30 Blackbird Center', '955-929-3859', 'abowering7@amazon.co.jp');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (9, 'eget congue eget semper', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'done', 420, 3, 90, 'Ula', 'Summerhayes', '4 Prairieview Street', '225-305-4920', 'usummerhayes8@qq.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (10, 'pellentesque eget', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 450, 2, 90, 'Anders', 'Goudman', '0 Mandrake Avenue', '928-892-0032', 'agoudman9@java.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (11, 'eget massa tempor', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'in process', 1440, 2, 60, 'Martguerita', 'Redier', '140 Scofield Drive', '986-522-4007', 'mrediera@youtu.be');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (12, 'varius nulla', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'in process', 750, 1, 240, 'Fitzgerald', 'Driussi', '330 Moulton Place', '930-511-3913', 'fdriussib@archive.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (13, 'lorem integer tincidunt ante', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 1290, 1, 30, 'Ailbert', 'Gorger', '122 Harper Crossing', '427-104-2050', 'agorgerc@elegantthemes.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (14, 'maecenas leo odio', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Quote Requested', 510, 1, 150, 'Grange', 'Bertot', '13 Hauk Road', '546-520-6471', 'gbertotd@naver.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (15, 'eu mi nulla ac', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'done', 720, 7, 240, 'Cindee', 'Bentick', '41356 Warner Avenue', '207-501-7550', 'cbenticke@pen.io');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (16, 'ultrices posuere cubilia curae', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'in process', 480, 4, 60, 'Phillipe', 'Phillipp', '7 Prentice Place', '886-856-8534', 'pphillippf@skyrock.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (17, 'purus aliquet at', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Quote Requested', 1290, 6, 60, 'Killie', 'MacGowan', '6877 Moland Street', '169-447-9841', 'kmacgowang@discovery.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (18, 'dui maecenas', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'in process', 570, 2, 240, 'Charmian', 'Sloan', '8153 Gulseth Court', '502-193-5022', 'csloanh@ow.ly');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (19, 'lectus pellentesque', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 150, 6, 60, 'Susanetta', 'Domokos', '709 Eagle Crest Road', '910-891-5842', 'sdomokosi@youtu.be');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (20, 'nulla suspendisse potenti cras', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'in process', 1410, 10, 120, 'Binnie', 'Carsberg', '506 Nova Junction', '438-422-3043', 'bcarsbergj@statcounter.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (21, 'habitasse platea', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Quote Requested', 1080, 3, 240, 'Verna', 'Goodbur', '9439 Hoepker Hill', '508-789-5603', 'vgoodburk@army.mil');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (22, 'id justo sit amet', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'in process', 330, 1, 90, 'Josefa', 'Willshee', '2271 Moland Circle', '821-389-7804', 'jwillsheel@mtv.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (23, 'sed accumsan', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'done', 1350, 3, 60, 'Selena', 'Cicchetto', '5474 Forest Road', '423-112-3857', 'scicchettom@plala.or.jp');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (24, 'massa id nisl venenatis', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'in process', 1140, 9, 30, 'Leonora', 'Saterthwait', '2699 Arkansas Junction', '546-874-3927', 'lsaterthwaitn@dailymail.co.uk');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (25, 'fusce posuere', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'done', 780, 4, 60, 'Iggie', 'Salmon', '04113 Stuart Pass', '960-765-3246', 'isalmono@nbcnews.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (26, 'ultrices enim', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'done', 180, 6, 240, 'Kristan', 'Drance', '91289 Lillian Junction', '915-668-4558', 'kdrancep@feedburner.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (27, 'nibh in', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'done', 870, 4, 60, 'Filmer', 'Higford', '0 Nobel Terrace', '308-119-1725', 'fhigfordq@tamu.edu');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (28, 'cubilia curae donec', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'in process', 480, 1, 90, 'Delilah', 'Beri', '72 Rieder Circle', '463-879-6378', 'dberir@mysql.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (29, 'vestibulum ac', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Quote Requested', 390, 10, 60, 'Rosemarie', 'Betty', '14683 Onsgard Pass', '469-727-5633', 'rbettys@quantcast.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (30, 'lacinia sapien quis', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'done', 840, 6, 150, 'Thatcher', 'Gayton', '83719 Claremont Drive', '994-760-5373', 'tgaytont@netscape.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (31, 'aliquam convallis nunc', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'in process', 150, 6, 180, 'Trueman', 'Lamlin', '6 Paget Park', '824-132-6426', 'tlamlinu@stumbleupon.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (32, 'nec dui luctus', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'done', 930, 1, 30, 'Goldi', 'Harrington', '5007 Russell Pass', '922-826-6691', 'gharringtonv@columbia.edu');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (33, 'rutrum nulla tellus', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'done', 480, 7, 210, 'Torrin', 'Jebb', '80465 Lillian Road', '862-289-6906', 'tjebbw@geocities.jp');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (34, 'eget tincidunt eget tempus', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Quote Requested', 1230, 5, 150, 'Caril', 'Ingleson', '93 Johnson Court', '855-853-2239', 'cinglesonx@4shared.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (35, 'rutrum at lorem integer', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'done', 1320, 3, 30, 'Martino', 'O''Loughnan', '74 Division Drive', '989-424-4334', 'moloughnany@cafepress.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (36, 'dis parturient montes nascetur', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Quote Requested', 930, 6, 240, 'Siouxie', 'Guidera', '4 Roth Alley', '199-877-2345', 'sguideraz@nasa.gov');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (37, 'donec pharetra magna', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 810, 7, 30, 'Benedick', 'Riccard', '89261 Farwell Park', '698-379-9402', 'briccard10@gov.uk');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (38, 'integer ac neque duis', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'done', 90, 8, 60, 'Jilleen', 'Deddum', '057 Summer Ridge Park', '525-661-1881', 'jdeddum11@fastcompany.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (39, 'nunc vestibulum', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'in process', 180, 10, 120, 'Sawyer', 'Mounfield', '216 Scoville Circle', '322-256-7157', 'smounfield12@arstechnica.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (40, 'sapien cursus vestibulum', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Quote Requested', 810, 7, 180, 'Shane', 'Fahey', '209 8th Crossing', '603-666-6796', 'sfahey13@cyberchimps.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (41, 'nec molestie', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'in process', 330, 9, 150, 'Ofilia', 'Kleinhaus', '0 Beilfuss Pass', '167-194-3328', 'okleinhaus14@google.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (42, 'vestibulum aliquet ultrices', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'done', 1350, 5, 60, 'Seth', 'Swynley', '8 Longview Crossing', '203-664-6551', 'sswynley15@engadget.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (43, 'morbi non lectus', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'in process', 1410, 2, 30, 'Caresse', 'Ioannou', '613 Eastwood Trail', '389-280-7081', 'cioannou16@nymag.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (44, 'dis parturient montes', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'done', 630, 9, 120, 'Lyssa', 'Klyn', '180 Namekagon Avenue', '170-314-0360', 'lklyn17@nationalgeographic.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (45, 'amet sem', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Quote Requested', 840, 10, 30, 'Anallise', 'Janik', '43933 Ohio Trail', '169-222-4437', 'ajanik18@wix.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (46, 'quam sapien varius ut', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 90, 9, 120, 'Deny', 'Nabbs', '24865 Corscot Way', '967-193-9891', 'dnabbs19@usa.gov');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (47, 'sagittis sapien cum sociis', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 120, 5, 90, 'Babara', 'Glenn', '85154 Ohio Lane', '919-600-0500', 'bglenn1a@edublogs.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (48, 'mauris lacinia sapien', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Quote Requested', 180, 2, 60, 'Bonnee', 'Sex', '51 Pleasure Center', '199-462-0342', 'bsex1b@tripod.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (49, 'aliquet maecenas leo', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'done', 600, 6, 120, 'Jessalyn', 'Whapple', '492 Butterfield Hill', '853-443-1697', 'jwhapple1c@rambler.ru');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (50, 'donec odio justo sollicitudin', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Quote Requested', 1350, 4, 60, 'Der', 'Isard', '9 Merchant Place', '178-168-1841', 'disard1d@wsj.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (51, 'nibh in', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'in process', 870, 3, 150, 'Merrill', 'Walaron', '8 Stephen Trail', '973-549-4789', 'mwalaron1e@latimes.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (52, 'vestibulum quam', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'done', 1320, 4, 30, 'Cacilie', 'Plom', '497 Clyde Gallagher Hill', '824-105-4250', 'cplom1f@facebook.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (53, 'ut ultrices vel', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Quote Requested', 540, 7, 240, 'Wynn', 'Rachuig', '27 Goodland Center', '952-136-0924', 'wrachuig1g@blinklist.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (54, 'nec nisi', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'in process', 1380, 2, 150, 'Caesar', 'Scantlebury', '0 Loomis Parkway', '947-750-0643', 'cscantlebury1h@businessinsider.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (55, 'nullam orci pede', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'done', 1230, 5, 240, 'Chariot', 'Pengelly', '8073 Spohn Center', '614-478-7902', 'cpengelly1i@ehow.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (56, 'quam sapien varius ut', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'in process', 1290, 5, 180, 'Nert', 'Leist', '577 Harbort Hill', '162-206-3274', 'nleist1j@istockphoto.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (57, 'lectus in', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'done', 240, 8, 120, 'Delbert', 'Caron', '62 Onsgard Road', '425-952-3026', 'dcaron1k@dyndns.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (58, 'porttitor id', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'in process', 690, 4, 90, 'Vivyanne', 'Witham', '2611 Monica Junction', '595-690-9604', 'vwitham1l@cocolog-nifty.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (59, 'in sagittis dui', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Quote Requested', 1170, 8, 210, 'Pauly', 'Treadwell', '4304 Dwight Trail', '488-284-9285', 'ptreadwell1m@sina.com.cn');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (60, 'nisl venenatis lacinia aenean', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'in process', 90, 2, 150, 'Remus', 'Flott', '5 Portage Junction', '814-111-5353', 'rflott1n@gnu.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (61, 'sit amet eros', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 270, 9, 90, 'Bride', 'Probyn', '174 Mcguire Hill', '273-853-0367', 'bprobyn1o@liveinternet.ru');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (62, 'nam congue risus semper', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'in process', 330, 4, 240, 'Tabor', 'Whorf', '8794 Lindbergh Terrace', '717-266-5954', 'twhorf1p@alexa.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (63, 'donec quis orci eget', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Quote Requested', 870, 3, 120, 'Ladonna', 'Bleier', '2 Briar Crest Point', '324-884-3628', 'lbleier1q@elegantthemes.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (64, 'nulla ut', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'done', 1230, 4, 210, 'Mannie', 'Hammant', '097 Shopko Pass', '715-771-1045', 'mhammant1r@gnu.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (65, 'cubilia curae', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'done', 930, 7, 240, 'Sallyann', 'Blandamore', '73 Green Ridge Crossing', '451-823-5447', 'sblandamore1s@alexa.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (66, 'nunc rhoncus dui', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Quote Requested', 570, 6, 180, 'Ermanno', 'Canet', '405 Gateway Crossing', '278-999-9286', 'ecanet1t@ameblo.jp');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (67, 'lacinia aenean sit', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'in process', 420, 8, 30, 'Lissi', 'Dubois', '44893 Graedel Pass', '447-350-4113', 'ldubois1u@blogtalkradio.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (68, 'ultrices enim lorem', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'done', 1020, 4, 150, 'Blinnie', 'Ohms', '1 Stuart Parkway', '318-445-1699', 'bohms1v@t.co');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (69, 'quis orci eget', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'in process', 690, 3, 210, 'Kissie', 'Ties', '72367 Lillian Plaza', '471-883-2853', 'kties1w@wikispaces.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (70, 'elit proin interdum', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'in process', 960, 2, 150, 'Stormi', 'Westlake', '8060 Lighthouse Bay Lane', '349-473-7577', 'swestlake1x@mlb.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (71, 'quis libero nullam', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'in process', 690, 6, 240, 'Christian', 'Cassin', '6 Drewry Drive', '899-995-5770', 'ccassin1y@walmart.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (72, 'eu sapien', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'done', 1140, 3, 240, 'Cherie', 'Furnell', '1 Kim Court', '727-692-0859', 'cfurnell1z@purevolume.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (73, 'felis fusce posuere', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 720, 2, 210, 'Ambrosi', 'Dressell', '38997 Monterey Hill', '811-545-2792', 'adressell20@nydailynews.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (74, 'ultricies eu nibh', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'done', 1350, 8, 180, 'Devi', 'Jumonet', '36379 Transport Hill', '576-756-7238', 'djumonet21@cam.ac.uk');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (75, 'suspendisse potenti in', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'in process', 810, 7, 240, 'Dugald', 'Raspison', '99 Dwight Junction', '940-617-9301', 'draspison22@gov.uk');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (76, 'cursus id turpis', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Quote Requested', 1170, 7, 150, 'Genevieve', 'Flitcroft', '76 Fallview Parkway', '850-842-9815', 'gflitcroft23@jimdo.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (77, 'cubilia curae donec pharetra', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'in process', 930, 10, 240, 'Thia', 'Tonnesen', '3937 Daystar Court', '199-726-0287', 'ttonnesen24@youtube.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (78, 'mattis pulvinar nulla pede', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'in process', 930, 7, 90, 'Joelie', 'Tinson', '1 Hermina Center', '290-204-8101', 'jtinson25@amazonaws.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (79, 'morbi sem', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Quote Requested', 660, 8, 210, 'Kristofer', 'Ferryman', '16270 Grim Center', '175-801-6303', 'kferryman26@mysql.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (80, 'consequat dui', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'done', 1110, 1, 150, 'Kaitlin', 'Spadeck', '653 Florence Place', '679-965-5436', 'kspadeck27@jugem.jp');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (81, 'in tempor turpis', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'done', 1200, 1, 30, 'Nancie', 'Nelsey', '319 Moulton Junction', '986-382-1411', 'nnelsey28@paypal.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (82, 'consectetuer adipiscing elit', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'in process', 480, 9, 180, 'Verge', 'Danell', '89343 Manitowish Parkway', '601-499-6966', 'vdanell29@cpanel.net');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (83, 'laoreet ut rhoncus aliquet', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'in process', 840, 6, 240, 'Belva', 'Stallibrass', '9 Marquette Street', '680-594-3149', 'bstallibrass2a@dailymail.co.uk');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (84, 'luctus et ultrices', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'in process', 450, 7, 180, 'Kliment', 'Wickendon', '99 Merrick Circle', '453-900-4956', 'kwickendon2b@amazon.de');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (85, 'nisl duis bibendum felis', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'done', 990, 5, 60, 'Erna', 'O'' Dornan', '3302 Talisman Avenue', '459-324-1811', 'eodornan2c@wp.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (86, 'placerat praesent blandit nam', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Quote Requested', 480, 4, 210, 'Anthe', 'Cordeau]', '1 Holy Cross Court', '209-368-9233', 'acordeau2d@reuters.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (87, 'augue quam', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 930, 3, 60, 'Francene', 'Raeside', '64024 Independence Street', '267-684-6806', 'fraeside2e@vk.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (88, 'vitae mattis nibh', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Quote Requested', 1170, 3, 30, 'Mil', 'Yeo', '7 Oriole Parkway', '725-977-8743', 'myeo2f@spotify.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (89, 'dictumst aliquam', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Quote Requested', 360, 6, 30, 'Feodora', 'Le Franc', '63 Hoepker Way', '752-725-4476', 'flefranc2g@seesaa.net');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (90, 'habitasse platea dictumst', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'in process', 120, 1, 150, 'Muriel', 'Richardet', '834 Pawling Place', '244-513-3388', 'mrichardet2h@discuz.net');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (91, 'donec ut mauris eget', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Quote Requested', 300, 7, 30, 'Kendre', 'Mandrier', '57 Prairie Rose Street', '742-884-4486', 'kmandrier2i@mtv.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (92, 'eget rutrum at', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'done', 540, 3, 240, 'Julian', 'Walas', '9513 Westport Park', '253-388-0580', 'jwalas2j@icq.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (93, 'nunc purus phasellus', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 1350, 8, 90, 'Lorelle', 'Costan', '17230 Farwell Point', '999-656-0266', 'lcostan2k@last.fm');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (94, 'aliquet maecenas leo odio', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'done', 990, 10, 240, 'Jesselyn', 'Dominico', '21 Aberg Junction', '434-940-0494', 'jdominico2l@unc.edu');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (95, 'non lectus aliquam sit', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'done', 30, 4, 210, 'Nicki', 'Yeoman', '7 Elka Court', '923-993-6465', 'nyeoman2m@abc.net.au');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (96, 'vestibulum proin eu', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 480, 5, 120, 'Arnaldo', 'Halliberton', '630 Truax Park', '257-997-9184', 'ahalliberton2n@deliciousdays.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (97, 'morbi odio odio', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'in process', 480, 5, 180, 'Guglielma', 'Gwynn', '6370 Doe Crossing Court', '527-672-5713', 'ggwynn2o@npr.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (98, 'nam tristique tortor eu', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'in process', 1170, 9, 90, 'Anestassia', 'Delaney', '87504 Bartelt Avenue', '411-648-0499', 'adelaney2p@opera.com');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (99, 'odio elementum', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'done', 780, 7, 90, 'Poppy', 'Chelsom', '13860 Claremont Lane', '787-121-5274', 'pchelsom2q@dyndns.org');
insert into Jobs (id, name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_Phone_number, customer_email) values (100, 'molestie lorem quisque ut', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'done', 450, 8, 240, 'Lorine', 'Fursland', '2857 Lotheville Road', '414-439-8638', 'lfursland2r@gizmodo.com');
