insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('viverra dapibus nulla suscipit', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'done', 180, 3, 120, 'Jillie', 'McClunaghan', '683 Lukken Plaza', 'Nikita', '811-673-5139', 'jmcclunaghan0@mayoclinic.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('vestibulum ante ipsum', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'in process', 1440, 7, 30, 'Cayla', 'Caseley', '75 Michigan Center', 'Dubai', '233-372-8819', 'ccaseley1@earthlink.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('habitasse platea dictumst etiam', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Quote Requested', 120, 3, 240, 'Waldon', 'Ubsdall', '442 Victoria Avenue', 'Tékane', '703-719-0583', 'wubsdall2@opera.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('at turpis a pede', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'done', 30, 5, 210, 'Susannah', 'Balden', '011 Oak Valley Point', 'Shuangta', '335-685-0891', 'sbalden3@deliciousdays.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('proin eu mi', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'done', 90, 5, 120, 'Joletta', 'MacKeever', '807 Fallview Circle', 'Wincrange', '464-575-0867', 'jmackeever4@wikia.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('rutrum rutrum', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'in process', 1080, 10, 180, 'Yasmeen', 'Pace', '8288 Coleman Plaza', 'Oyonnax', '814-926-0171', 'ypace5@businessinsider.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('non pretium quis lectus', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'done', 630, 1, 30, 'Thedric', 'Thoms', '47 High Crossing Parkway', 'Pátmos', '476-784-7345', 'tthoms6@ucoz.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('montes nascetur ridiculus mus', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Quote Requested', 300, 5, 60, 'Marthe', 'Loughhead', '478 Gateway Alley', 'Miraflores', '814-307-4371', 'mloughhead7@amazon.co.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ('morbi quis tortor', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'done', 240, 1, 150, 'Odo', 'Wisden', '2873 Myrtle Avenue', 'Lazaro Cardenas', '248-285-7046', 'owisden8@sciencedaily.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nunc viverra dapibus', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'done', 60, 3, 240, 'Seline', 'Peyto', '96135 Melby Pass', 'Shitun', '817-621-4733', 'speyto9@phpbb.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'est donec', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Quote Requested', 300, 3, 180, 'Elwyn', 'Sydry', '2847 Sunbrook Junction', 'Volgograd', '951-692-9281', 'esydrya@skyrock.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'feugiat et eros vestibulum', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'done', 120, 5, 150, 'Nancy', 'Cahillane', '6 Vera Junction', 'Balbalan', '425-260-6623', 'ncahillaneb@amazon.de');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'consectetuer adipiscing elit', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'done', 210, 5, 150, 'Virgie', 'MacGorrie', '53 Sachtjen Street', 'Paradela', '213-660-0143', 'vmacgorriec@washington.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ut erat', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 1080, 10, 90, 'Lorenzo', 'Ducaen', '578 Novick Street', 'Napoli', '473-741-3689', 'lducaend@springer.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'risus auctor sed', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Quote Requested', 210, 4, 30, 'Adrea', 'Whatling', '6543 Talmadge Trail', 'Sūrīān', '588-950-4245', 'awhatlinge@theglobeandmail.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nec molestie', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Quote Requested', 570, 2, 30, 'Annissa', 'Newens', '9635 Blaine Trail', 'Nordeste', '502-681-2396', 'anewensf@ft.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'a feugiat et', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'done', 630, 1, 240, 'Lon', 'Raulstone', '2 Lyons Crossing', 'Bente', '527-272-5427', 'lraulstoneg@cafepress.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'rutrum nulla', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'in process', 330, 9, 180, 'Abran', 'Desmond', '470 Manley Alley', 'Mashizhai', '639-369-4888', 'adesmondh@surveymonkey.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ut mauris eget massa', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Quote Requested', 210, 10, 30, 'Danyelle', 'Bulward', '5888 Dryden Place', 'Houxi', '823-971-0694', 'dbulwardi@salon.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ac nibh fusce', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Quote Requested', 330, 8, 60, 'Tiffanie', 'Charrier', '61666 Buena Vista Parkway', 'Rosebank', '536-779-9428', 'tcharrierj@npr.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'magna vulputate', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Quote Requested', 1020, 1, 30, 'Emelia', 'Proby', '508 Marcy Avenue', 'Esil', '647-401-8527', 'eprobyk@economist.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sit amet', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'in process', 600, 5, 30, 'Marchall', 'Vakhonin', '48169 Hanover Park', 'Huntington', '304-994-9919', 'mvakhoninl@unblog.fr');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'elementum pellentesque quisque porta', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Quote Requested', 510, 6, 180, 'Rhonda', 'Stefi', '67 Loeprich Plaza', 'Ngarus', '524-664-3889', 'rstefim@phoca.cz');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'cubilia curae duis faucibus', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Quote Requested', 750, 10, 60, 'Kit', 'Hevner', '5 Stang Alley', 'Shisui', '463-729-4950', 'khevnern@sciencedirect.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sed magna at nunc', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Quote Requested', 420, 1, 30, 'Sky', 'Imorts', '9 Laurel Drive', 'Nykarleby', '547-675-0049', 'simortso@imageshack.us');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'laoreet ut', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'in process', 1020, 4, 180, 'Karel', 'Ponton', '19 Kedzie Hill', 'Jardinópolis', '544-233-0558', 'kpontonp@vimeo.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ac leo pellentesque ultrices', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'in process', 120, 10, 240, 'Julienne', 'Edwinson', '2 Novick Pass', 'Registro', '988-883-5062', 'jedwinsonq@is.gd');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'libero convallis eget', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'in process', 1140, 3, 120, 'Thom', 'Riquet', '7 Ruskin Way', 'Bherāmāra', '609-740-8591', 'triquetr@addthis.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sem praesent', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'in process', 1230, 8, 120, 'Cash', 'Thebeaud', '8057 Farragut Drive', 'Albarraque', '337-687-6802', 'cthebeauds@macromedia.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'viverra diam vitae', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'done', 510, 5, 240, 'Pen', 'Masic', '853 Granby Road', 'Włosienica', '128-896-0019', 'pmasict@apache.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nibh in hac habitasse', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'in process', 600, 3, 60, 'Margaretta', 'Cazin', '164 Shoshone Way', 'Rungkam', '631-454-9917', 'mcazinu@microsoft.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ipsum primis', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'done', 540, 10, 120, 'Sherie', 'Arnholtz', '20030 Lerdahl Drive', 'Yala', '181-392-9252', 'sarnholtzv@miibeian.gov.cn');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nullam orci', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Quote Requested', 960, 5, 240, 'Maryjane', 'Flaxman', '57 Novick Point', 'Pringgoboyo', '298-485-5833', 'mflaxmanw@indiegogo.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'dui luctus rutrum nulla', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Quote Requested', 480, 9, 120, 'Tremayne', 'Snelle', '6 Birchwood Crossing', 'Jacareí', '539-930-1747', 'tsnellex@youtu.be');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'donec diam neque', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'done', 1200, 4, 180, 'Sharity', 'Locket', '825 Tennessee Park', 'Santo Niño', '766-760-8927', 'slockety@utexas.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'posuere nonummy integer', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'in process', 600, 8, 240, 'Giusto', 'Snalom', '92836 Hoffman Center', 'Pokrovka', '767-230-9561', 'gsnalomz@altervista.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'rhoncus dui vel', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'in process', 1380, 4, 30, 'Hobey', 'Lepper', '432 Menomonie Lane', 'Kotabumi', '585-986-5614', 'hlepper10@blogspot.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'porttitor id consequat', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'in process', 30, 6, 90, 'Ardys', 'Whitford', '0 7th Circle', 'Cayambe', '143-121-6102', 'awhitford11@shinystat.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ligula vehicula consequat', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'in process', 1170, 10, 150, 'Melina', 'Phoenix', '44 Glendale Drive', 'Stráž nad Nisou', '616-882-7790', 'mphoenix12@photobucket.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nulla ultrices aliquet', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'done', 630, 2, 60, 'Udell', 'Gascoigne', '59666 Summit Street', 'Muara', '114-474-2901', 'ugascoigne13@shop-pro.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'magna bibendum imperdiet', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'in process', 330, 9, 240, 'Florie', 'Marjoram', '45 Southridge Circle', 'Pinyug', '534-754-6658', 'fmarjoram14@google.ru');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'donec quis orci eget', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'done', 150, 4, 60, 'Ursuline', 'Burchatt', '7 Carberry Crossing', 'Verkhozim', '963-912-5476', 'uburchatt15@unesco.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'lorem quisque ut', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'in process', 330, 2, 150, 'Shalna', 'Thebeaud', '1 Namekagon Trail', 'Jiaozuo', '955-935-0017', 'sthebeaud16@trellian.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'orci pede venenatis', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'in process', 1290, 8, 90, 'Kassi', 'Cope', '278 Lakewood Court', 'Krajan Alastengah', '397-295-3062', 'kcope17@exblog.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nulla elit ac', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 270, 4, 210, 'Elsworth', 'Abrahamsen', '034 Johnson Park', 'Opočno', '633-659-4435', 'eabrahamsen18@shareasale.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'lobortis ligula sit amet', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Quote Requested', 210, 2, 180, 'Rosina', 'Ravenhill', '765 Walton Court', 'Wenfeng Zhen', '474-940-8963', 'rravenhill19@nba.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'erat vestibulum sed', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'in process', 1260, 1, 150, 'Reginauld', 'Dubs', '7427 Kennedy Point', 'Yonggu', '484-876-3280', 'rdubs1a@slideshare.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'eleifend pede libero quis', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 1440, 1, 120, 'Anders', 'Ambroisin', '5185 Mcguire Avenue', 'Vila Velha', '781-171-2329', 'aambroisin1b@godaddy.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'massa tempor', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'in process', 1350, 3, 240, 'Emilia', 'Greir', '592 Westend Hill', 'Dama', '225-180-9425', 'egreir1c@tiny.cc');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'odio curabitur', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Quote Requested', 750, 8, 240, 'Berne', 'Walworth', '350 Fuller Street', 'Solok Timur', '424-480-5226', 'bwalworth1d@scientificamerican.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ac consequat metus sapien', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'in process', 360, 5, 210, 'Tomasina', 'Daglish', '307 West Trail', 'Passal', '650-605-4053', 'tdaglish1e@dion.ne.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nisi nam ultrices', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'in process', 1020, 4, 180, 'Matty', 'Trickett', '3965 Hauk Park', 'Taixi', '179-299-4927', 'mtrickett1f@usa.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'hac habitasse', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Quote Requested', 180, 3, 240, 'Elsi', 'Kettle', '6498 Charing Cross Drive', 'Yaroslavskiy', '587-274-3491', 'ekettle1g@discuz.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'vel est donec odio', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'done', 90, 3, 150, 'Reginauld', 'Gaskill', '96798 Warrior Street', 'Dajing', '959-935-0973', 'rgaskill1h@amazon.co.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'integer aliquet massa', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 1290, 4, 120, 'Dannie', 'McCleod', '2339 Macpherson Park', 'Marne-la-Vallée', '539-709-3269', 'dmccleod1i@stanford.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'hendrerit at', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Quote Requested', 270, 8, 180, 'Dagmar', 'O'' Mullan', '28 John Wall Point', 'Zürich', '961-466-3354', 'domullan1j@ycombinator.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'pellentesque quisque', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'done', 1140, 1, 30, 'Brigid', 'Dublin', '98 Nancy Lane', 'Gori', '207-385-8610', 'bdublin1k@bandcamp.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sed sagittis', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'done', 930, 7, 240, 'Rosabella', 'Chyuerton', '58 Heath Park', 'Goléré', '358-917-0224', 'rchyuerton1l@chicagotribune.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ut erat id', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'done', 570, 2, 240, 'Oswell', 'Witham', '057 Sachtjen Plaza', 'Kelasuri', '455-805-3249', 'owitham1m@gmpg.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'erat eros', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'done', 300, 6, 30, 'Linnea', 'Frankish', '656 Mosinee Place', 'Nikhom Kham Soi', '992-681-7556', 'lfrankish1n@nbcnews.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'lorem integer tincidunt ante', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Quote Requested', 30, 1, 240, 'Adi', 'Mayman', '38 Anzinger Terrace', 'Taekas', '733-396-0503', 'amayman1o@ed.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'volutpat erat quisque', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Quote Requested', 840, 4, 180, 'Doloritas', 'Probey', '168 Oakridge Trail', 'Rusip', '979-187-7642', 'dprobey1p@51.la');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'magna vulputate luctus', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Quote Requested', 120, 10, 30, 'Juli', 'Verecker', '8607 Meadow Vale Avenue', 'Zlataritsa', '994-624-0020', 'jverecker1q@imageshack.us');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ornare consequat lectus', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'in process', 1080, 10, 240, 'Aveline', 'Cuthbertson', '6 Schmedeman Pass', 'Basel', '601-436-1784', 'acuthbertson1r@networksolutions.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'duis bibendum felis', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'in process', 720, 5, 90, 'Guglielma', 'Roskam', '25976 Clarendon Circle', 'Tanuma', '655-451-8438', 'groskam1s@aboutads.info');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'viverra diam', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'done', 1020, 2, 180, 'Dorree', 'Coniff', '6 Waxwing Court', 'Tianhe', '203-933-4333', 'dconiff1t@hibu.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'pretium nisl ut volutpat', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Quote Requested', 30, 4, 210, 'Aretha', 'Craddock', '670 High Crossing Place', 'Nyalindung', '334-205-7471', 'acraddock1u@zdnet.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'ullamcorper augue a', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Quote Requested', 1200, 5, 90, 'Tiffie', 'Butts', '88 Kropf Plaza', 'Al ‘Ashshah', '354-884-7775', 'tbutts1v@amazon.co.uk');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'semper interdum mauris', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Quote Requested', 330, 1, 90, 'Perry', 'Joyes', '74011 Delladonna Junction', 'Taldyqorghan', '291-146-2800', 'pjoyes1w@squidoo.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'dui vel', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 1050, 3, 180, 'Shamus', 'Trosdall', '336 Larry Plaza', 'Dhidhdhoo', '738-157-0421', 'strosdall1x@liveinternet.ru');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'faucibus orci luctus', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'done', 330, 10, 240, 'Enrica', 'Bramble', '936 Brown Terrace', 'Hupalivka', '974-102-6481', 'ebramble1y@cafepress.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'quisque ut erat', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'done', 240, 3, 150, 'Waverly', 'Trower', '862 Cardinal Street', 'Pacaraos', '866-377-3919', 'wtrower1z@ezinearticles.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'dapibus at diam nam', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 330, 4, 120, 'Felizio', 'Corbould', '6945 Hansons Court', 'Batibati', '434-890-1562', 'fcorbould20@newyorker.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sit amet cursus', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'done', 1140, 3, 120, 'Brodie', 'Wiz', '18959 Rusk Alley', 'Xiawuqi', '115-892-9350', 'bwiz21@123-reg.co.uk');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'convallis tortor risus', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'in process', 420, 2, 60, 'Gabey', 'Peert', '413 Northland Parkway', 'Dhali', '675-493-3447', 'gpeert22@about.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'pellentesque volutpat dui', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'done', 30, 10, 30, 'Edeline', 'Ludovici', '6052 Kensington Point', 'Kičevo', '338-237-6614', 'eludovici23@chron.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'magna at', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'in process', 720, 1, 240, 'Elmore', 'Able', '2 Commercial Avenue', 'Finspång', '400-619-0942', 'eable24@mlb.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'penatibus et magnis', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 1350, 10, 210, 'Jarrett', 'Cudihy', '07 Melvin Point', 'Chernyshkovskiy', '261-693-7657', 'jcudihy25@blogspot.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nascetur ridiculus', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Quote Requested', 240, 3, 90, 'Latisha', 'Skully', '62443 Veith Plaza', 'Bouzov', '228-404-2564', 'lskully26@weather.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sociis natoque penatibus', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'in process', 690, 7, 90, 'Caryl', 'Gonzales', '62 Bluejay Way', 'Daytona Beach', '386-167-1903', 'cgonzales27@tinyurl.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'cubilia curae', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 240, 4, 60, 'Leanna', 'Kellegher', '2086 Carberry Avenue', 'Rodniki', '385-205-8552', 'lkellegher28@liveinternet.ru');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'blandit nam nulla integer', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'done', 930, 6, 120, 'Tristam', 'Baldinotti', '9 Springview Alley', 'Farkaždin', '183-582-6018', 'tbaldinotti29@chronoengine.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'eget nunc donec quis', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'done', 480, 1, 240, 'Rodger', 'Creffeild', '9308 Marcy Court', 'Hrušica', '158-396-8254', 'rcreffeild2a@paginegialle.it');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'vestibulum sagittis', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 1230, 10, 90, 'Lauren', 'Line', '1456 Marquette Junction', 'Hancheng', '224-558-6930', 'lline2b@oaic.gov.au');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'consequat lectus in est', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'done', 30, 6, 120, 'Sephira', 'Vamplew', '922 Declaration Plaza', 'Nankang', '940-840-9721', 'svamplew2c@spotify.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'pellentesque at nulla', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'in process', 1230, 1, 90, 'Esther', 'Traut', '18873 International Terrace', 'Lleida', '670-995-5457', 'etraut2d@umn.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'convallis duis consequat', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'in process', 600, 5, 60, 'Barbe', 'Landreth', '8368 Fallview Plaza', 'Tatsuno', '908-520-9782', 'blandreth2e@example.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'curae mauris viverra', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'done', 150, 6, 150, 'Concettina', 'Shurlock', '77 Rowland Park', 'Dulangan', '202-953-1021', 'cshurlock2f@clickbank.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'posuere metus vitae ipsum', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'in process', 120, 8, 60, 'Jilleen', 'Perl', '3455 Russell Trail', 'Campraksanta', '264-458-7575', 'jperl2g@sourceforge.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'at velit', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Quote Requested', 690, 3, 150, 'Delinda', 'Hilling', '312 Alpine Parkway', 'Ballyboden', '716-627-9525', 'dhilling2h@jiathis.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'vel dapibus', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'done', 1080, 6, 210, 'Townsend', 'Coling', '7744 Dovetail Road', 'Lancaster', '717-126-4386', 'tcoling2i@comcast.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'tincidunt eget', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Quote Requested', 1350, 4, 150, 'Inna', 'Pesterfield', '6 Hoard Park', 'Zhengji', '741-697-4001', 'ipesterfield2j@ox.ac.uk');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nam ultrices libero non', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'in process', 300, 10, 60, 'Dianna', 'Pendle', '824 5th Plaza', 'Pacora', '335-431-5474', 'dpendle2k@list-manage.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'nulla nunc', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'in process', 1200, 9, 30, 'Jackquelin', 'Szimoni', '94441 Miller Center', 'Jugezhuang', '934-890-3684', 'jszimoni2l@cdc.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'risus praesent lectus', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'done', 1110, 8, 180, 'Maribeth', 'Geeves', '30 Lighthouse Bay Pass', 'Jiangyi', '762-614-9288', 'mgeeves2m@bandcamp.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'laoreet ut rhoncus', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'done', 720, 2, 30, 'Glynis', 'Semon', '45 Burning Wood Circle', 'Chowki Jamali', '559-901-1005', 'gsemon2n@boston.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'orci pede venenatis', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'in process', 1200, 6, 240, 'Willetta', 'Salla', '83614 Sachs Point', 'Sukosari', '578-830-7097', 'wsalla2o@google.pl');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'aliquet pulvinar sed nisl', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 1200, 4, 210, 'Gardie', 'Maplethorp', '8423 Twin Pines Alley', 'Zaječov', '345-961-8657', 'gmaplethorp2p@senate.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'pede justo lacinia eget', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'done', 420, 7, 120, 'Jilly', 'Lorentz', '81 Mccormick Way', 'Xinying', '310-751-3841', 'jlorentz2q@homestead.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_phone_number, customer_email) values ( 'sollicitudin vitae consectetuer eget', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Quote Requested', 510, 2, 30, 'Daune', 'Saby', '5 Nova Junction', 'Meicheng', '194-969-9999', 'dsaby2r@shinystat.com');
