insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('porttitor pede justo', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'done', 1200, 8, 90, 'Rourke', 'Blackaller', '1948 Waubesa Pass', 'Venda', '713-154-4452', 'rblackaller0@goo.gl');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('mauris ullamcorper purus', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 1380, 10, 120, 'Randi', 'Condit', '6 Kensington Parkway', 'Bom Despacho', '280-785-1137', 'rcondit1@sciencedaily.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('dapibus augue vel', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'in process', 1230, 6, 120, 'Xymenes', 'D''Elias', '58 Hovde Circle', 'Zalantun', '870-720-0108', 'xdelias2@ted.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lacinia sapien', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'Quote Requested', 720, 5, 90, 'Chrystal', 'Deluca', '69233 Paget Parkway', 'Sundsvall', '723-308-2878', 'cdeluca3@imgur.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sit amet', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'Quote Requested', 900, 7, 30, 'Rudie', 'Vasyukhin', '8297 Golf Junction', 'Yujiawu', '894-335-6316', 'rvasyukhin4@booking.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('nulla ac enim', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'in process', 690, 5, 210, 'Lemar', 'Freire', '70 Crownhardt Road', 'Jacksonville', '904-954-4300', 'lfreire5@exblog.jp');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sapien iaculis congue', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Quote Requested', 1110, 5, 180, 'Bamby', 'Nickoll', '35 Straubel Street', 'Arcoverde', '835-489-3765', 'bnickoll6@wunderground.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('libero convallis eget eleifend', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'in process', 330, 2, 60, 'Suzanna', 'Crosston', '6 Northridge Way', 'Cuispes', '590-119-0521', 'scrosston7@dmoz.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('suscipit a', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'done', 1200, 2, 210, 'Angelle', 'Merali', '1178 Delladonna Way', 'Abbotsford', '143-273-0207', 'amerali8@kickstarter.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vestibulum eget vulputate', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'in process', 1080, 4, 240, 'Danyelle', 'Van de Velde', '75 Walton Street', 'Uitiuhtuan', '521-845-5790', 'dvandevelde9@intel.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('hendrerit at', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'in process', 1350, 6, 180, 'Patsy', 'Bound', '342 Bunting Trail', 'Umeå', '692-211-6823', 'pbounda@hubpages.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('molestie nibh in lectus', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'in process', 1440, 5, 90, 'Janaya', 'Passby', '681 Prairie Rose Terrace', 'Berthierville', '711-847-9517', 'jpassbyb@skype.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('rhoncus mauris enim', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'done', 1110, 8, 210, 'Jock', 'Doggett', '9026 Ridgeway Circle', 'Kotlovka', '378-805-4793', 'jdoggettc@bing.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('in imperdiet et', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Quote Requested', 930, 1, 120, 'Cassey', 'Luscombe', '124 Prentice Street', 'Laka', '270-621-5443', 'cluscombed@pen.io');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('at feugiat', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'in process', 60, 2, 30, 'Jamison', 'Petre', '08276 Ramsey Street', 'Amiens', '272-552-4426', 'jpetree@php.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vivamus vel nulla eget', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 90, 7, 180, 'Sofia', 'Frizzell', '8662 5th Street', 'Chiang Rai', '883-747-7988', 'sfrizzellf@yolasite.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('pellentesque ultrices mattis odio', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'in process', 1290, 4, 120, 'Jeramey', 'Latch', '53034 Veith Place', 'Shin’ichi', '702-702-6633', 'jlatchg@google.com.au');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('nec condimentum neque', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Quote Requested', 1290, 6, 30, 'Gus', 'Putland', '59327 Cambridge Circle', 'Midleton', '634-840-0117', 'gputlandh@woothemes.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('tempor convallis nulla', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'done', 960, 3, 30, 'Roger', 'Paulillo', '8 Texas Drive', 'Kobrinskoye', '488-912-2313', 'rpaulilloi@arizona.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vulputate ut ultrices vel', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'done', 1200, 6, 150, 'Anita', 'Schwandermann', '656 Briar Crest Center', 'Grecheskoye', '392-897-2366', 'aschwandermannj@springer.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('non lectus aliquam sit', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'in process', 780, 3, 240, 'Rachael', 'Masserel', '74 Hooker Circle', 'Belūsovka', '266-563-8823', 'rmasserelk@answers.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sit amet consectetuer', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'in process', 1020, 4, 180, 'Rog', 'Dudliston', '162 Sunnyside Avenue', 'Nizhniy Tagil', '419-523-0166', 'rdudlistonl@histats.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('turpis adipiscing lorem vitae', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'in process', 810, 6, 210, 'Godiva', 'Spowart', '3064 Gerald Drive', 'Satrejan', '996-400-8104', 'gspowartm@earthlink.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('enim leo rhoncus sed', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Quote Requested', 150, 9, 90, 'Nicolais', 'Mellodey', '64 Fremont Point', 'Slyudyanka', '302-352-4784', 'nmellodeyn@cisco.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('libero convallis eget', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Quote Requested', 180, 9, 90, 'Valle', 'Stit', '09074 Hallows Pass', 'Halimaung Jaya (F-3)', '589-324-3368', 'vstito@tinypic.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('tellus nulla', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'in process', 1230, 5, 60, 'Veronika', 'Arnoult', '25 Debs Avenue', 'Millerovo', '882-125-5130', 'varnoultp@free.fr');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('et eros vestibulum', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Quote Requested', 330, 7, 30, 'Dougie', 'Beszant', '87919 Spaight Pass', 'Xingtai', '871-228-8929', 'dbeszantq@alibaba.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('consequat nulla', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'done', 750, 10, 90, 'Amata', 'Handsheart', '661 Maywood Trail', 'Rucava', '882-735-7630', 'ahandsheartr@cornell.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('duis faucibus', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'in process', 30, 2, 120, 'Sarina', 'Dumsday', '579 Mesta Pass', 'Guaratuba', '109-582-2953', 'sdumsdays@foxnews.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sed tristique in', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'done', 90, 6, 240, 'Madeleine', 'Chaytor', '5 Leroy Center', 'Dartang', '298-542-2975', 'mchaytort@sbwire.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('ultrices aliquet maecenas leo', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'done', 30, 4, 120, 'Sarette', 'Hanley', '84 Tennessee Circle', 'Wissembourg', '934-324-1388', 'shanleyu@forbes.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('in porttitor pede justo', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 120, 6, 210, 'Grete', 'Jurkiewicz', '41 Hollow Ridge Park', 'Lawonda', '811-229-8098', 'gjurkiewiczv@nsw.gov.au');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sapien iaculis congue', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 150, 2, 210, 'Decca', 'McGrory', '35 Green Ridge Alley', 'São Caetano do Sul', '702-940-8705', 'dmcgroryw@de.vu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vestibulum quam sapien', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'in process', 1050, 7, 240, 'Mannie', 'Hadgkiss', '488 Daystar Hill', 'Paucar', '154-550-8713', 'mhadgkissx@mashable.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('metus sapien ut', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'done', 1440, 5, 120, 'Shalom', 'Matchitt', '31518 Derek Pass', 'Zhen’an', '969-709-5379', 'smatchitty@virginia.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sapien arcu sed', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'in process', 300, 7, 90, 'Leeanne', 'Black', '51 Browning Way', 'Ust’-Kalmanka', '781-323-0716', 'lblackz@slate.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('duis bibendum morbi non', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'in process', 840, 10, 150, 'Frasquito', 'Creaven', '2281 Elgar Crossing', 'Niamey', '623-788-7650', 'fcreaven10@loc.gov');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('neque sapien placerat ante', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'in process', 1050, 9, 210, 'Pyotr', 'Lumpkin', '59 Upham Lane', 'Beverwijk', '636-917-6760', 'plumpkin11@forbes.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('aliquam augue quam', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'in process', 270, 3, 120, 'Peria', 'Murrhaupt', '506 Brentwood Hill', 'Salwá', '498-273-4471', 'pmurrhaupt12@wikispaces.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('enim lorem ipsum dolor', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Quote Requested', 1050, 7, 240, 'Hubey', 'Seyffert', '06 Dixon Crossing', 'Intendente Alvear', '510-846-0110', 'hseyffert13@furl.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('ligula sit amet eleifend', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'done', 1110, 2, 180, 'Quinn', 'Perocci', '5 Clarendon Circle', 'Jangas', '740-795-3940', 'qperocci14@ihg.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('imperdiet nullam', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Quote Requested', 120, 8, 60, 'Noach', 'Fellenor', '1 Sommers Terrace', 'Muhur', '261-635-1122', 'nfellenor15@loc.gov');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('quam turpis adipiscing', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 450, 2, 150, 'Wanda', 'Pattinson', '35 La Follette Avenue', 'Caidian', '422-101-0927', 'wpattinson16@slashdot.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('ipsum dolor sit', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'in process', 1320, 1, 90, 'Lynea', 'Burr', '48563 Hoard Avenue', 'Roubaix', '848-169-3502', 'lburr17@statcounter.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('erat id', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'done', 1170, 6, 150, 'Selene', 'Wanley', '6027 Milwaukee Road', 'Bil‘īn', '906-278-8667', 'swanley18@google.co.jp');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lobortis ligula sit amet', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'done', 150, 6, 90, 'Lindsay', 'Iacobacci', '3 Kennedy Circle', 'Caldas da Rainha', '395-657-5981', 'liacobacci19@over-blog.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('rutrum neque', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'in process', 840, 7, 120, 'Rooney', 'Yeldon', '6836 Truax Point', 'Nove-Misto', '369-202-5655', 'ryeldon1a@ask.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('ac lobortis vel dapibus', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'done', 570, 1, 150, 'Wernher', 'Spofford', '1 Sherman Center', 'Ostrowsko', '392-264-1544', 'wspofford1b@oracle.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('imperdiet sapien', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'done', 1110, 6, 120, 'Hogan', 'Lygo', '0715 Crescent Oaks Road', 'Naawan', '531-347-3276', 'hlygo1c@icio.us');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('eu orci', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Quote Requested', 630, 10, 210, 'Shannah', 'Coverley', '25 Union Point', 'Sumenep', '403-967-3265', 'scoverley1d@slideshare.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lobortis convallis tortor risus', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'done', 270, 3, 30, 'Adriane', 'Pegram', '72 Florence Alley', 'Hashtpar', '987-753-4092', 'apegram1e@blogger.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vel pede', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'in process', 270, 10, 210, 'Corey', 'Hartas', '81 Burning Wood Road', 'Rokem Barat', '209-170-9492', 'chartas1f@shop-pro.jp');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('praesent id massa', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'done', 1170, 7, 210, 'Christiano', 'Quinlan', '96366 Hagan Lane', 'Kawm Ḩamādah', '391-258-4826', 'cquinlan1g@uol.com.br');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('at turpis a pede', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Quote Requested', 1440, 1, 150, 'Lodovico', 'Glendza', '96672 Hudson Trail', 'La Rioja', '442-392-8529', 'lglendza1h@bandcamp.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('nulla tellus in', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'done', 420, 3, 180, 'Ree', 'Bollam', '7 Kedzie Crossing', 'Wakaseko', '707-594-9992', 'rbollam1i@w3.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('tortor duis mattis', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'done', 990, 8, 240, 'Enrico', 'MacGiffin', '5799 Almo Crossing', 'Lagodekhi', '758-376-9042', 'emacgiffin1j@twitter.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('in faucibus orci luctus', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'in process', 1110, 4, 120, 'Gipsy', 'Lejeune', '094 Texas Street', 'Qilin', '248-890-0399', 'glejeune1k@shop-pro.jp');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('integer tincidunt ante', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'done', 900, 9, 180, 'Almeta', 'MacSkeagan', '0 Anhalt Court', 'Kuncen', '483-795-9428', 'amacskeagan1l@nyu.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lacus purus', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'in process', 900, 7, 90, 'Vidovik', 'Treamayne', '7 Prairie Rose Parkway', 'Jincheng', '197-617-8121', 'vtreamayne1m@sogou.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sapien arcu sed augue', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'done', 390, 7, 60, 'Ulla', 'Mallows', '4749 Hoepker Plaza', 'Longgao', '810-540-5622', 'umallows1n@bbb.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('dictumst aliquam augue quam', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Quote Requested', 960, 7, 240, 'Chere', 'Le-Good', '8830 Carberry Street', 'Waina', '545-458-7379', 'clegood1o@simplemachines.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('id luctus nec', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Quote Requested', 720, 4, 60, 'Tommie', 'Leemans', '08864 Jenifer Terrace', 'Ngajum', '711-699-1987', 'tleemans1p@soup.io');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('mauris non ligula', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Quote Requested', 120, 4, 120, 'Judas', 'Lomasny', '9 Delaware Avenue', 'Xian’an', '146-791-2955', 'jlomasny1q@pen.io');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('pede lobortis', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Quote Requested', 960, 7, 150, 'Eal', 'Wreath', '8 Bowman Parkway', 'Heilbronn', '191-276-5281', 'ewreath1r@parallels.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('justo maecenas', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'done', 840, 8, 60, 'Lauren', 'Pitfield', '1791 Johnson Pass', 'Huiqi', '373-269-1487', 'lpitfield1s@mac.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('quisque arcu libero', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Quote Requested', 810, 10, 90, 'Eldridge', 'Ondrus', '8983 8th Road', 'Raojān', '119-309-0590', 'eondrus1t@arstechnica.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lorem vitae mattis', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'in process', 720, 1, 120, 'Shawn', 'Bayley', '3077 Ludington Alley', 'Roanne', '649-244-4905', 'sbayley1u@facebook.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('erat tortor', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'done', 30, 3, 150, 'Jamil', 'Willas', '428 Valley Edge Parkway', 'Paris 14', '353-755-4008', 'jwillas1v@pbs.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('at diam nam', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'in process', 120, 8, 30, 'Renae', 'Alpes', '74 Hudson Park', 'Fengshan', '232-256-5912', 'ralpes1w@cbslocal.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('maecenas tincidunt lacus', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 1170, 3, 180, 'Terrie', 'Beckerleg', '619 Florence Center', 'Mabunga', '714-226-6639', 'tbeckerleg1x@sphinn.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sapien sapien non', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'in process', 1050, 9, 180, 'Bernie', 'Jodrellec', '5 Haas Lane', 'Mvomero', '155-495-6353', 'bjodrellec1y@earthlink.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vulputate nonummy maecenas tincidunt', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 270, 7, 30, 'Giuditta', 'Bowdidge', '1037 Russell Center', 'Mesa', '480-941-1584', 'gbowdidge1z@xing.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('purus aliquet at feugiat', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'Quote Requested', 1380, 5, 150, 'Angelika', 'Burston', '93 Goodland Junction', 'Vyshchetarasivka', '304-674-2426', 'aburston20@qq.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('justo in blandit', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'done', 90, 2, 180, 'Hendrik', 'MacKeeg', '25 Lake View Alley', 'Kongolo', '810-325-3481', 'hmackeeg21@ucoz.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('mi integer ac', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'in process', 1080, 6, 240, 'Edyth', 'Holwell', '5 Warrior Terrace', 'Sabirabad', '628-771-5838', 'eholwell22@reuters.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('quis libero', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'in process', 180, 5, 150, 'Hillier', 'Hulmes', '56 Elmside Alley', 'Faqqū‘ah', '407-500-9482', 'hhulmes23@clickbank.net');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('est et', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'in process', 540, 8, 180, 'Amble', 'Kornousek', '16483 American Point', 'Chavárion', '248-366-8040', 'akornousek24@forbes.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('maecenas ut massa quis', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'in process', 840, 8, 90, 'Cecilia', 'Snoad', '95 Londonderry Trail', 'Íquira', '824-958-9887', 'csnoad25@cargocollective.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('feugiat non', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'done', 1050, 8, 210, 'Ardith', 'Aaronson', '414 American Way', 'Chwałowice', '841-502-6009', 'aaaronson26@go.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('consectetuer adipiscing elit', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Quote Requested', 900, 6, 30, 'Aloisia', 'Crutchley', '75900 Spohn Avenue', 'Tigre', '937-347-8525', 'acrutchley27@yellowbook.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('in faucibus orci', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'in process', 570, 7, 90, 'Jacquette', 'Schroter', '26 Dapin Road', 'Ollachea', '176-545-7108', 'jschroter28@tumblr.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('purus aliquet', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'in process', 30, 5, 180, 'Gerardo', 'Weiser', '7163 Fulton Court', 'Iralaya', '146-488-7065', 'gweiser29@state.tx.us');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('dui maecenas tristique', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Quote Requested', 840, 4, 120, 'Cynthea', 'Grice', '0492 Commercial Road', 'Lubango', '380-404-4966', 'cgrice2a@umich.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('amet cursus', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'in process', 1020, 4, 120, 'Riccardo', 'Boak', '94993 Scott Lane', 'Shangju', '832-497-7038', 'rboak2b@wisc.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sed tristique in', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 240, 5, 240, 'Kaleena', 'Rowan', '00 Summer Ridge Place', 'Bojongnangka', '420-371-5090', 'krowan2c@msu.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('a libero nam', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'in process', 360, 9, 210, 'Anne', 'Lathbury', '66370 Grover Way', 'Melissochóri', '236-695-7764', 'alathbury2d@dot.gov');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('porttitor lacus at turpis', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Quote Requested', 1350, 1, 60, 'Brianna', 'Kobsch', '2 Texas Pass', 'Alor Star', '294-251-2079', 'bkobsch2e@sbwire.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('est quam pharetra', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'in process', 1020, 10, 90, 'Vivyanne', 'MacMychem', '2 Kings Center', 'Águas Vermelhas', '190-182-9374', 'vmacmychem2f@twitter.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lorem id', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'done', 360, 1, 150, 'Anabella', 'Jeandel', '40257 Hoepker Avenue', 'Ancenis', '541-310-8080', 'ajeandel2g@twitter.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('id lobortis convallis tortor', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'done', 1080, 7, 210, 'Artie', 'Hearl', '6 Forest Run Drive', 'Cikaras', '825-448-1605', 'ahearl2h@wikipedia.org');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('justo pellentesque', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Quote Requested', 1380, 2, 180, 'Emery', 'Landal', '618 Gale Way', 'Choropampa', '709-681-1910', 'elandal2i@wikispaces.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('ut erat curabitur', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Quote Requested', 600, 4, 60, 'Jerrold', 'Busek', '1 Lotheville Alley', 'Parungjawa', '508-938-8447', 'jbusek2j@census.gov');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('iaculis justo', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 1260, 7, 240, 'Chiarra', 'Taphouse', '129 Arapahoe Parkway', 'Granja', '387-983-8484', 'ctaphouse2k@harvard.edu');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('pede ac diam cras', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'in process', 150, 4, 180, 'Cody', 'Dehmel', '345 Lakewood Gardens Terrace', 'Rudnya', '742-849-9153', 'cdehmel2l@marriott.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('rhoncus aliquet pulvinar', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'in process', 30, 7, 90, 'Ailsun', 'Tremethack', '00 Clove Point', 'Buliok', '293-676-3177', 'atremethack2m@qq.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('convallis duis consequat dui', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'done', 1140, 5, 180, 'Rivkah', 'Kildahl', '4757 Oneill Terrace', 'Ḩukūmat-e Shīnkaī', '476-193-6134', 'rkildahl2n@domainmarket.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('enim sit', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'in process', 210, 1, 120, 'Alyse', 'Shorton', '716 Steensland Park', 'Batasan', '396-165-8392', 'ashorton2o@surveymonkey.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('elit proin risus praesent', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 1440, 8, 150, 'Gerti', 'Caghy', '003 Arizona Hill', 'Shalamzār', '254-378-0579', 'gcaghy2p@intel.com');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('erat nulla tempus', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'in process', 690, 9, 30, 'Lucky', 'Bracken', '2 Eggendart Crossing', 'Thị Trấn Na Hang', '766-719-4041', 'lbracken2q@is.gd');
insert into Jobs (name, notes, status, total_estimate_time, total_estimate_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('vel est', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'done', 780, 4, 120, 'Michele', 'Bourton', '42 Morningstar Court', 'Jingcheng', '302-102-6271', 'mbourton2r@yahoo.com');
