insert into Tasks (name, description) values ('Planting', 'Etiam pretium iaculis justo.');
insert into Tasks (name, description) values ('transplanting', 'Sed ante.');
insert into Tasks (name, description) values ('maintaining flowers and plants', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into Tasks (name, description) values ('greenhouse and nursery stock', 'Donec ut dolor.');
insert into Tasks (name, description) values ('Installing rock gardens', 'Vivamus tortor. Duis mattis egestas metus.');
insert into Tasks (name, description) values ('ponds', 'Quisque ut erat. Curabitur gravnisi at nibh. In hac habitasse platea dictumst.');
insert into Tasks (name, description) values ('decks', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Tasks (name, description) values ('drainage systems', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Tasks (name, description) values ('fences', 'Phasellus in felis. Donec semper sapien a libero.');
insert into Tasks (name, description) values ('planters and playground equipment', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
