insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 99.7, 4, 3.99, 'Hobard', 'Eloi', '6 Surrey Plaza', 'Hagondange', '851-973-2225', 'heloi0@yahoo.co.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Quote Requested', 6.73, 9, 1.72, 'Lillis', 'Eard', '6470 Grayhawk Hill', 'Fengtai', '458-459-2216', 'leard1@comcast.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'done', 99.96, 9, 2.24, 'Jennee', 'Salla', '2 Randy Lane', 'Maslog', '766-880-3050', 'jsalla2@earthlink.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'in process', 68.13, 2, 3.48, 'Gusti', 'Draysay', '1388 Fieldstone Circle', 'Chengnan', '898-112-2296', 'gdraysay3@pinterest.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'in process', 6.81, 4, 1.16, 'Felipa', 'Whitely', '19 Oak Valley Crossing', 'São Paulo', '820-243-1243', 'fwhitely4@google.ca');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Quote Requested', 23.73, 10, 4.56, 'Cinderella', 'Cocklie', '46 Butternut Center', 'Inuvik', '876-579-9620', 'ccocklie5@theguardian.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Quote Requested', 28.55, 8, 2.56, 'Ermina', 'Frankiss', '94 Thackeray Pass', 'Sillon', '187-903-2424', 'efrankiss6@digg.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'Quote Requested', 37.77, 3, 2.88, 'Corrinne', 'Toe', '3863 Rusk Junction', 'Nanqiao', '346-632-8963', 'ctoe7@ask.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Quote Requested', 74.18, 7, 3.57, 'Omar', 'Proske', '37 Orin Hill', 'Samoš', '768-642-0526', 'oproske8@shareasale.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'done', 7.38, 10, 4.97, 'Doralynn', 'Cavil', '3451 Schlimgen Court', 'Ruyigi', '656-774-0659', 'dcavil9@gmpg.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Quote Requested', 1.1, 2, 4.38, 'Kordula', 'Swash', '274 Vidon Lane', 'Lyasny', '540-378-0337', 'kswasha@wunderground.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Quote Requested', 24.51, 2, 4.21, 'Celinka', 'Winsome', '371 Prentice Trail', 'Madīnat Lab‘ūs', '423-736-8128', 'cwinsomeb@51.la');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'in process', 19.98, 10, 3.79, 'Hugibert', 'Mowett', '1 Kenwood Center', 'Les Sables-d''Olonne', '916-639-6714', 'hmowettc@tripadvisor.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'in process', 86.63, 10, 4.92, 'Pen', 'Tiddy', '6 6th Circle', 'Heichengzi', '267-584-8625', 'ptiddyd@ycombinator.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting grass', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Quote Requested', 96.38, 8, 3.81, 'Sela', 'Hencke', '5394 Canary Circle', 'Huatai', '713-520-8779', 'shenckee@themeforest.net');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'in process', 14.91, 1, 4.71, 'Corey', 'Corhard', '520 Di Loreto Circle', 'Zelenodolsk', '825-359-4610', 'ccorhardf@google.com.br');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Quote Requested', 12.34, 7, 3.36, 'Tuesday', 'Michelotti', '45591 Lerdahl Hill', 'Sinargalih', '489-223-0765', 'tmichelottig@twitpic.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Quote Requested', 73.26, 4, 1.98, 'Ashia', 'Pollack', '20437 Moulton Trail', 'Asquipata', '537-660-9313', 'apollackh@homestead.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'in process', 73.95, 2, 3.1, 'Carolyne', 'Mote', '6899 Londonderry Avenue', 'Konārak', '990-516-6916', 'cmotei@mashable.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'in process', 5.32, 5, 2.17, 'Windham', 'Kuhwald', '17 Bonner Lane', 'Luofang', '649-462-8768', 'wkuhwaldj@cloudflare.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'in process', 15.41, 8, 1.12, 'Kingsley', 'Decort', '7 Main Center', 'Palca', '731-191-4801', 'kdecortk@is.gd');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'done', 43.61, 4, 4.27, 'Vick', 'Bum', '0 Duke Lane', 'Pionerskiy', '930-364-2774', 'vbuml@diigo.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Quote Requested', 76.2, 8, 3.13, 'Vera', 'Kirdsch', '466 4th Lane', 'Kishorganj', '896-162-3201', 'vkirdschm@51.la');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Quote Requested', 32.63, 7, 1.44, 'Jannel', 'Cliss', '835 Sunfield Avenue', 'Figueira', '339-496-2969', 'jclissn@w3.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'in process', 61.57, 8, 2.98, 'Hillier', 'Griggs', '60 Victoria Center', 'Kalnibolotskaya', '111-584-3837', 'hgriggso@ehow.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'done', 75.48, 9, 3.97, 'Frieda', 'Segebrecht', '70328 Truax Road', 'Tamandaré', '859-615-8947', 'fsegebrechtp@i2i.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'done', 45.52, 8, 4.54, 'Ginelle', 'Minci', '83157 Forest Dale Trail', 'Fastiv', '385-863-2330', 'gminciq@networksolutions.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting grass', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Quote Requested', 69.67, 1, 2.61, 'Gale', 'Grisdale', '65 Lakeland Terrace', 'Ansan-si', '224-336-9011', 'ggrisdaler@eepurl.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Quote Requested', 54.86, 3, 2.19, 'Anabella', 'Edeson', '2436 Lighthouse Bay Way', 'Casilda', '774-777-4885', 'aedesons@joomla.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'in process', 84.5, 2, 2.7, 'Georgiana', 'Filippov', '095 Sachtjen Place', 'Valday', '983-203-9480', 'gfilippovt@reddit.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'done', 43.54, 2, 4.37, 'Harper', 'Hudless', '561 Service Park', 'Ciepielów', '801-735-8391', 'hhudlessu@blogs.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'in process', 94.98, 6, 4.57, 'Gale', 'Laux', '75 Gale Parkway', 'Guilmaro', '547-551-4870', 'glauxv@oakley.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Quote Requested', 8.91, 7, 1.94, 'Jase', 'Gibberd', '7065 Ludington Center', 'Piskavica', '929-290-5101', 'jgibberdw@about.me');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'in process', 95.44, 8, 3.33, 'Amy', 'Liger', '8 Cody Way', 'Mengcheng Chengguanzhen', '205-952-9975', 'aligerx@scribd.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'done', 39.41, 9, 4.46, 'Ulberto', 'Linguard', '1 Warbler Way', 'Gilowice', '142-661-5840', 'ulinguardy@sciencedaily.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'done', 44.03, 6, 4.96, 'Petronella', 'Fettes', '64384 Old Shore Pass', 'Cileueur', '636-516-1598', 'pfettesz@desdev.cn');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'in process', 60.55, 6, 4.11, 'Carmon', 'Scoggan', '2420 Milwaukee Road', 'Ketapang', '699-709-2278', 'cscoggan10@webs.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Quote Requested', 98.95, 3, 2.62, 'Beulah', 'Clelle', '93187 Grim Circle', 'La Paz', '678-176-1820', 'bclelle11@dot.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'in process', 31.07, 7, 1.99, 'Ramsay', 'Passie', '945 Northridge Alley', 'Sortavala', '411-561-2165', 'rpassie12@hhs.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Quote Requested', 54.68, 8, 2.67, 'Wallis', 'Threadgall', '42 Center Terrace', 'Fangjun', '891-518-6290', 'wthreadgall13@japanpost.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'in process', 86.84, 8, 2.36, 'Vanessa', 'Buchanan', '8384 Acker Way', 'Mencon', '160-705-2894', 'vbuchanan14@cyberchimps.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'done', 82.68, 2, 3.41, 'Mary', 'Blagbrough', '9298 Bayside Avenue', 'Alcala', '406-769-4266', 'mblagbrough15@ning.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'in process', 26.0, 6, 2.91, 'Valida', 'Camilletti', '564 Parkside Center', 'Yukhnov', '919-184-6306', 'vcamilletti16@hexun.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'done', 58.94, 4, 2.07, 'Karyl', 'Shackelton', '102 Oak Junction', 'Kista', '509-418-0436', 'kshackelton17@wp.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Quote Requested', 27.1, 5, 1.66, 'Filide', 'Canto', '44 Blue Bill Park Plaza', 'Sarmanovo', '673-762-3978', 'fcanto18@simplemachines.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'done', 86.87, 2, 3.76, 'Brocky', 'Bamford', '22449 Cascade Street', 'Dengok', '492-349-3657', 'bbamford19@qq.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'in process', 77.58, 3, 3.1, 'Iver', 'Heelis', '3 Grayhawk Drive', 'Idrinskoye', '794-615-6989', 'iheelis1a@ca.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Quote Requested', 50.15, 10, 2.94, 'Missy', 'Celiz', '0 Macpherson Park', 'Fengyi', '732-865-0914', 'mceliz1b@networkadvertising.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Quote Requested', 20.22, 6, 3.58, 'Doralynn', 'Spancock', '5 David Street', 'Al Jaghbūb', '478-301-3429', 'dspancock1c@blog.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'done', 99.09, 4, 3.94, 'Marilin', 'Robilliard', '323 Golden Leaf Place', 'Totok', '673-549-2190', 'mrobilliard1d@1688.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'done', 26.64, 9, 3.74, 'Meredithe', 'Delete', '37 Bayside Park', 'Roshnik', '311-116-1739', 'mdelete1e@samsung.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('The house on top of the hill', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'done', 42.76, 5, 3.8, 'Joyann', 'Ilyasov', '9 Eagle Crest Court', 'Mungui', '464-466-2205', 'jilyasov1f@who.int');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'done', 35.74, 7, 1.45, 'Gregg', 'Sexty', '82791 Eastlawn Park', 'Pompéu', '657-166-9769', 'gsexty1g@amazon.co.jp');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'in process', 69.54, 6, 3.57, 'Ody', 'Coaster', '71602 Schmedeman Avenue', 'Lijiang', '441-697-7658', 'ocoaster1h@discovery.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'in process', 60.83, 1, 1.28, 'Dolores', 'Lendrem', '10 Village Circle', 'Gununglarang', '640-421-5862', 'dlendrem1i@mozilla.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'in process', 12.25, 3, 1.42, 'Gratiana', 'Belsham', '9 Crowley Plaza', 'Mutum', '416-489-2798', 'gbelsham1j@artisteer.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('The house on top of the hill', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Quote Requested', 61.14, 5, 3.93, 'Towny', 'Sawdon', '986 Crescent Oaks Alley', 'Jatinagara', '761-644-8884', 'tsawdon1k@posterous.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Quote Requested', 38.24, 2, 4.96, 'Edythe', 'Wooland', '22643 Columbus Drive', 'Balas', '710-240-4445', 'ewooland1l@mapquest.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Quote Requested', 28.81, 2, 1.59, 'Thorndike', 'Boult', '85 Calypso Park', 'Bandar-e Torkaman', '119-655-3746', 'tboult1m@networksolutions.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'in process', 28.27, 7, 3.91, 'Vania', 'Myerscough', '60697 Center Crossing', 'Cipaku', '637-178-6620', 'vmyerscough1n@freewebs.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Quote Requested', 60.38, 6, 2.0, 'Kenna', 'Kleine', '534 Dottie Plaza', 'Komsomol’sk', '490-880-2520', 'kkleine1o@wisc.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Quote Requested', 85.29, 3, 3.66, 'Sibbie', 'Moseby', '40 Everett Plaza', 'Alah Sāy', '411-809-3998', 'smoseby1p@amazon.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'done', 99.28, 6, 1.41, 'Keeley', 'Murford', '9432 North Road', 'Aileu', '487-119-9690', 'kmurford1q@twitter.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 51.38, 6, 4.15, 'Mendy', 'Strutton', '8811 Katie Hill', 'Saguenay', '258-147-3320', 'mstrutton1r@reference.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Quote Requested', 87.72, 10, 1.38, 'Katuscha', 'Gillings', '2844 Upham Way', 'Settat', '174-715-2250', 'kgillings1s@indiegogo.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'in process', 67.64, 2, 4.4, 'Elias', 'Kirkland', '531 Lillian Circle', 'Jajar', '748-120-8943', 'ekirkland1t@techcrunch.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Quote Requested', 69.46, 3, 4.14, 'Yvor', 'Larkworthy', '3150 Service Street', 'Nahrīn', '946-762-7250', 'ylarkworthy1u@uiuc.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'done', 15.15, 10, 2.31, 'Rodd', 'Baroche', '3 Dryden Street', 'Cienfuegos', '131-520-6799', 'rbaroche1v@mozilla.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'in process', 51.38, 7, 4.44, 'Ware', 'Brownsey', '732 Mendota Court', 'Johanneshov', '623-928-7889', 'wbrownsey1w@nyu.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 53.81, 10, 4.74, 'Tull', 'Harbard', '68982 Northfield Parkway', 'Huacrachuco', '477-175-0788', 'tharbard1x@samsung.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Quote Requested', 2.85, 6, 4.41, 'Devina', 'Cansdale', '965 Village Green Trail', 'Kamakura', '676-408-0692', 'dcansdale1y@virginia.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Quote Requested', 46.91, 4, 2.99, 'Kerry', 'Askem', '72 Southridge Pass', 'Zhichanghe', '481-461-5493', 'kaskem1z@java.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'done', 59.94, 8, 1.86, 'Moselle', 'Vina', '0 Summit Center', 'Asemanis', '351-213-1474', 'mvina20@cocolog-nifty.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Quote Requested', 87.95, 7, 1.91, 'Benyamin', 'Winspire', '88 Bonner Court', 'Bistrica ob Sotli', '434-728-1567', 'bwinspire21@virginia.edu');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'in process', 53.5, 9, 1.28, 'Gilberte', 'Proger', '593 Huxley Plaza', 'Bandar-e Ganāveh', '969-573-7690', 'gproger22@oakley.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('The house on top of the hill', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'done', 89.9, 8, 3.32, 'Evvie', 'Hagergham', '7 Crowley Pass', 'Wanju', '956-432-8733', 'ehagergham23@time.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'done', 82.03, 3, 2.66, 'Skipper', 'LLelweln', '68 4th Place', 'Saint Petersburg', '286-593-4132', 'sllelweln24@bigcartel.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Quote Requested', 64.76, 10, 3.45, 'Hermione', 'Honnicott', '1669 Pine View Alley', 'Qal‘ah-ye Na‘īm', '682-573-9505', 'hhonnicott25@reverbnation.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Quote Requested', 83.4, 8, 1.71, 'Channa', 'Nitto', '9002 Spohn Park', 'Cirangrang', '259-319-4801', 'cnitto26@loc.gov');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new front yard', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'in process', 1.98, 4, 2.08, 'Philippine', 'Storey', '3196 Judy Parkway', 'Anchorage', '907-568-6353', 'pstorey27@xrea.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Quote Requested', 85.48, 7, 4.76, 'Rex', 'Brunnen', '3 Holmberg Park', 'Partesh', '227-955-1112', 'rbrunnen28@chronoengine.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Quote Requested', 23.4, 6, 3.72, 'Suzanna', 'Deboo', '3581 Monterey Hill', 'Bollnäs', '317-225-9920', 'sdeboo29@economist.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'in process', 70.74, 10, 3.31, 'Teressa', 'Durbin', '3297 Harbort Park', 'Blagnac', '786-587-4635', 'tdurbin2a@chron.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('designing new backyeard', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'in process', 90.41, 8, 2.21, 'Tobe', 'Bloxsum', '29039 Prentice Parkway', 'San Andres', '569-653-1125', 'tbloxsum2b@nature.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('sanding the streets', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Quote Requested', 7.0, 9, 1.36, 'Justinn', 'Bridewell', '24001 Scoville Point', 'Banjar Beratan', '855-512-7332', 'jbridewell2c@ox.ac.uk');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Quote Requested', 76.39, 2, 4.18, 'Doralynne', 'Hick', '1315 Eggendart Court', 'Albania', '538-705-0526', 'dhick2d@pcworld.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Quote Requested', 10.26, 8, 1.48, 'Hattie', 'Peyton', '07663 Sheridan Park', 'Przesmyki', '769-348-9989', 'hpeyton2e@delicious.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'done', 1.19, 1, 1.03, 'Jyoti', 'Twelve', '61355 Grayhawk Center', 'Banjar Dukuh', '612-990-9903', 'jtwelve2f@mtv.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting a flowers', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'done', 56.88, 9, 3.97, 'Wynny', 'Nock', '6095 Stone Corner Center', 'Sulitair', '349-201-0086', 'wnock2g@apache.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'in process', 52.36, 9, 1.27, 'Earl', 'Munnis', '759 Miller Junction', 'Hoçisht', '101-113-2795', 'emunnis2h@woothemes.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Quote Requested', 44.52, 10, 1.21, 'Iosep', 'Beves', '8101 Sunfield Junction', 'Knin', '652-529-9738', 'ibeves2i@creativecommons.org');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('leveling the backyad', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Quote Requested', 28.46, 8, 2.24, 'Alic', 'De Banke', '9132 Forest Way', 'Liangyaping', '528-493-9599', 'adebanke2j@4shared.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('shovelling for appt complex', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Quote Requested', 13.36, 4, 2.01, 'Morse', 'Halvosen', '202 Valley Edge Park', 'Kratié', '275-516-5231', 'mhalvosen2k@blogger.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('The house on top of the hill', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Quote Requested', 98.03, 3, 1.53, 'Kala', 'Beachamp', '4656 Crescent Oaks Hill', 'Sobral', '150-154-4013', 'kbeachamp2l@alexa.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('transplanting grass', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'in process', 61.77, 8, 1.64, 'Em', 'Tayt', '34894 Vermont Way', 'Leloboko', '316-486-6624', 'etayt2m@sciencedaily.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('removing a tree', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'done', 30.48, 7, 3.89, 'Marylinda', 'Pharaoh', '9633 Johnson Park', 'Dordrecht', '578-587-5937', 'mpharaoh2n@weebly.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('lawn mowing', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'done', 41.63, 7, 3.77, 'Den', 'Nelle', '11 Merrick Junction', 'Sidaharja', '220-949-3592', 'dnelle2o@icq.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('installing fence in banff', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'done', 15.46, 2, 1.1, 'Fredi', 'Bolte', '41 Sherman Plaza', 'Wang Sam Mo', '946-977-0589', 'fbolte2p@friendfeed.com');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('plowing the snow', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Quote Requested', 76.02, 3, 3.28, 'Page', 'Jolland', '9931 Marquette Circle', 'Mitú', '422-563-4659', 'pjolland2q@independent.co.uk');
insert into Jobs (name, notes, status, estimate_total_time, estimate_total_workers, estimate_travel_time, customer_first_name, customer_last_name, customer_address, customer_city, customer_Phone_number, customer_email) values ('new comunity', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'done', 56.79, 7, 4.68, 'Inness', 'Ledwith', '8414 Haas Plaza', 'Dvurechensk', '569-809-0014', 'iledwith2r@slideshare.net');
