insert into Tasks (name, description) values ('Planting', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into Tasks (name, description) values ('Transplanting', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Tasks (name, description) values ('Garden Maintenance', 'Sed ante.');
insert into Tasks (name, description) values ('Lawn Mowing', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into Tasks (name, description) values ('Tree Removal', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Tasks (name, description) values ('Ponds and Water Features', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Tasks (name, description) values ('Brush Removal', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Tasks (name, description) values ('Pruneing', 'Suspendisse ornare consequat lectus.');
insert into Tasks (name, description) values ('Fence Building', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Tasks (name, description) values ('Trimming', 'Phasellus in felis.');
insert into Tasks (name, description) values ('Sod Installation', 'Phasellus in felis.');
insert into Tasks (name, description) values ('Retaining Walls', 'Phasellus in felis.');
insert into Tasks (name, description) values ('Weeding', 'Phasellus in felis.');
insert into Tasks (name, description) values ('Snow Removal', 'Phasellus in felis.');
insert into Tasks (name, description) values ('Drainage Control', 'Phasellus in felis.');