insert into Tasks (name, description) values ('Planting', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into Tasks (name, description) values ('transplanting', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Tasks (name, description) values ('maintaining flowers and plants', 'Sed ante.');
insert into Tasks (name, description) values ('greenhouse and nursery stock', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into Tasks (name, description) values ('Installing rock gardens', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Tasks (name, description) values ('ponds', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Tasks (name, description) values ('decks', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Tasks (name, description) values ('drainage systems', 'Suspendisse ornare consequat lectus.');
insert into Tasks (name, description) values ('fences', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Tasks (name, description) values ('planters and playground equipment', 'Phasellus in felis.');
