DROP TABLE IF EXISTS Assignments CASCADE;
DROP TABLE IF EXISTS Skills CASCADE;
DROP TABLE IF EXISTS Requirements CASCADE;

CREATE TABLE Assignments (
  id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES jobs(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  date_time VARCHAR(255),
  estimate_hrs INTEGER
);

CREATE TABLE Skills (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
  skill_level INTEGER
);

CREATE TABLE Requirements (
  id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES jobs(id) ON DELETE CASCADE,
  task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
  difficulty INTEGER,
  estimate_time INTEGER,
  estimate_workers INTEGER
);